# Generated by Django 3.2.9 on 2021-11-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211120_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
