# Generated by Django 3.2.9 on 2021-11-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='seat',
            field=models.IntegerField(),
        ),
    ]
