# Generated by Django 3.2.9 on 2021-11-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0003_auto_20211121_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
