# Generated by Django 3.2.9 on 2021-11-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0004_userbook_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='vaccine_certificate',
        ),
    ]
