# Generated by Django 3.2.9 on 2021-11-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0005_remove_userbook_vaccine_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
    ]
