# Generated by Django 3.2.9 on 2021-11-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCourses', '0023_auto_20211123_2230'),
        ('schedular', '0006_schedule_booked_seats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('course', 'date', 'start_time', 'end_time')},
        ),
    ]
