# Generated by Django 3.2.9 on 2021-11-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0007_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='students_per_col',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='students_per_row',
            field=models.IntegerField(default=0),
        ),
    ]
