# Generated by Django 3.2.9 on 2021-11-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0008_auto_20211125_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='students_per_col',
        ),
    ]
