# Generated by Django 3.2.9 on 2021-11-26 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0009_remove_schedule_students_per_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='booked_seats',
        ),
        migrations.AlterField(
            model_name='userbook',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schedular.schedule'),
        ),
    ]
