# Generated by Django 3.2.9 on 2021-11-26 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appCourses', '0038_auto_20211126_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faculty_name',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 14, 54, 6, 190636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 14, 54, 6, 191633, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='registercourse',
            name='date_of_registering',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 14, 54, 6, 193632, tzinfo=utc)),
        ),
    ]
