# Generated by Django 3.2.9 on 2021-11-28 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appCourses', '0041_auto_20211126_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='university_id',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 4, 49, 8, 463562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 4, 49, 8, 463562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='registercourse',
            name='date_of_registering',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 4, 49, 8, 464557, tzinfo=utc)),
        ),
    ]
