# Generated by Django 3.2.9 on 2021-11-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211116_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
