# Generated by Django 3.2.9 on 2021-11-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='designation',
            field=models.CharField(default='Student', max_length=20),
        ),
    ]
