# Generated by Django 3.2.9 on 2021-11-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20211126_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions_number',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='total_marks',
        ),
    ]
