# Generated by Django 3.2.9 on 2021-11-23 14:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appCourses', '0020_auto_20211123_1946'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('question', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('message_html', models.TextField(editable=False)),
                ('rank', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCourses.course')),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvotes', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvotes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rank'],
                'unique_together': {('user', 'course', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCourses.course')),
                ('downvotes', models.ManyToManyField(blank=True, related_name='a_downvotes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='discussionForum.answer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussionForum.query')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='a_upvotes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
